"""Constantes del proyecto: especies del experimento, rutas e hiperparámetros."""

from pathlib import Path

PRUEBA = "75_objetivo_ft"

VARIABLES_GLOBALES: dict[str, object] = {
    "PRUEBA": PRUEBA,
    "RUTA_BASE": Path(__file__).resolve().parent.parent / "data",
    "EXTENSIONES_VALIDAS": {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp"},

    # Excluidas por falta de datos o malos resultados: Planothidium_fp (3 imágenes), Eunotia exigua (6),
    # Fragilaria radians (3), Gomphonema pumilum var. rigidum (ninguna; solo hay pumilum a secas),
    # Achnanthidium delmontii (malos resultados), Achnanthidium rostropyrenaicum (muy pocas).
    "ESPECIES_FILTRADAS": {
        "Achnanthidium_atomoides",
        "Achnanthidium_caravelense",
        "Achnanthidium_catenatum",
        "Achnanthidium_druartii",
        "Achnanthidium_eutrophilum",
        "Achnanthidium_exile",
        "Achnanthidium_fp",
        "Achnanthidium_minutissimum",
        "Achnanthidium_pyrenaicum",
        "Achnanthidium_rivulare",
        "Amphora_pediculus",
        "Aulacoseira_granulata",
        "Cocconeis_lineata",
        "Cocconeis_pediculus",
        "Cocconeis_placentula_var_euglypta",
        "Craticula_accomoda",
        "Cyclotella_atomus",
        "Cymbella_excisiformis_var_excisiformis",
        "Cymbella_parva",
        "Debris",
        "Denticula_tenuis",
        "Diatoma_moniliformis",
        "Diatoma_vulgaris",
        "Discostella_pseudostelligera",
        "Encyonema_fp",
        "Encyonema_minutum",
        "Encyonema_reichardtii",
        "Encyonema_silesiacum",
        "Encyonema_ventricosum",
        "Encyonopsis_fp",
        "Encyonopsis_minuta",
        "Epithemia_adnata",
        "Epithemia_fp",
        "Fistulifera_saprophila",
        "Fragilaria_fp",
        "Fragilaria_pararumpens",
        "Fragilaria_perminuta",
        "Fragilaria_vaucheriae",
        "Fragments",
        "Gomphonema_angustivalva",
        "Gomphonema_fp",
        "Gomphonema_minusculum",
        "Gomphonema_minutum",
        "Gomphonema_parvulum_f_saprophilum",
        "Gomphonema_pumilum_var_elegans",
        "Gomphonema_rhombicum",
        "Humidophila_contenta",
        "Karayevia_clevei_var_clevei",
        "Mayamaea_permitis",
        "Melosira_fp",
        "Melosira_varians",
        "Navicula_capitatoradiata",
        "Navicula_cryptotenella",
        "Navicula_cryptotenelloides",
        "Navicula_gregaria",
        "Navicula_lanceolata",
        "Navicula_notha",
        "Navicula_tripunctata",
        "Nitzschia_amphibia",
        "Nitzschia_capitellata",
        "Nitzschia_desertorum",
        "Nitzschia_fonticola",
        "Nitzschia_fp",
        "Nitzschia_frustulum_var_frustulum",
        "Nitzschia_inconspicua",
        "Nitzschia_palea_var_palea",
        "Nitzschia_paleacea",
        "Nitzschia_soratensis",
        "Planothidium_frequentissimum",
        "Planothidium_lanceolatum",
        "Reimeria_sinuata",
        "Reimeria_sp",
        "Rhoicosphenia_abbreviata",
        "Staurosira_venter",
        "Stephanodiscus_hantzschii",
        "Tabellaria_flocculosa",
        "Tabellaria_fp",
    },

    "MINIMO_IMAGENES_POR_ESPECIE": 5,
    "EXPONENTE_PESO_CLASE": 0.3,  # más alto = más peso a las clases minoritarias (rango 0.3-1.0)
    "LABEL_SMOOTHING": 0.05,
    "WEIGHT_DECAY": 0.0001,

    # Clasificador (MLP sobre el CLS de DINOv2)
    "DIM_EMBEDDING": 768,
    "DIM_CAPA_1": 512,
    "DIM_CAPA_2": 256,
    "DROPOUT_CAPA_1": 0.3,
    "DROPOUT_CAPA_2": 0.2,
}
